# Generated by Django 4.2 on 2023-04-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Art_name', models.CharField(max_length=100)),
                ('date_Modified', models.DateField(auto_now_add=True)),
                ('level', models.CharField(choices=[('Goal & Initiatives', 'GI'), ('Products & Service', 'PS'), ('Data & Information', 'DI'), ('Network & Infrastructure', 'NI')], max_length=50)),
                ('version', models.CharField(max_length=50)),
            ],
        ),
    ]
