# Generated by Django 4.2 on 2023-04-09 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date_modified', models.DateField(auto_now_add=True)),
                ('level', models.CharField(choices=[('GI', 'Goals & Initiatives'), ('PS', 'Products & Services'), ('DI', 'Data & Information'), ('SA', 'Systems & Applications'), ('NI', 'Networks & Infrastructure')], default='GI', max_length=10)),
            ],
        ),
    ]
